// Code generated by sqlc. DO NOT EDIT.

package si_bank

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   float64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be postive
	Amount    int64
	CreatedAt time.Time
}
